"""Initial migration

Revision ID: 36811fc4bfdf
Revises: 5076bcf45262
Create Date: 2023-09-22 21:31:58.191026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36811fc4bfdf'
down_revision = '5076bcf45262'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('library', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=15),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('library', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=15),
               nullable=False)

    # ### end Alembic commands ###
